import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './style.css';
import { Header } from '~/components/Layout/Header/Header';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
     title: 'Create Next App',
     description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
     return (
          <html lang="en">
               <body className={inter.className}>
                    <Header />
                    <div className="pt-16"> {children}</div>
               </body>
          </html>
     );
}
